version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    image: tg_arbuz-bot:latest
    env_file: ./cfg/.env